{{- if .Values.proxyConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dheera_ai.fullname" . }}-config
data:
  config.yaml: |
{{ .Values.proxy_config | toYaml | indent 6 }}
{{- end }}