{{- if .Values.db.deployStandalone -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dheera_ai.fullname" . }}-dbcredentials
data:
  # Password for the "postgres" user
  postgres-password: {{ ( index .Values.postgresql.auth "postgres-password") | default "dheera_ai" | b64enc }}
  username: {{ .Values.postgresql.auth.username | default "dheera_ai" | b64enc }}
  password: {{ .Values.postgresql.auth.password | default "dheera_ai" | b64enc }}
type: Opaque
{{- end -}}