repos:
-   repo: local
    hooks:
    -   id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        files: ^(dheera_ai/|dheera_ai_proxy_extras/|enterprise/)
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        files: (dheera_ai/|dheera_ai_proxy_extras/|enterprise/).*\.py
        exclude: ^dheera_ai/__init__.py$
    # -   id: black
    #     name: black
    #     entry: poetry run black
    #     language: system
    #     types: [python]
    #     files: (dheera_ai/|dheera_ai_proxy_extras/|enterprise/).*\.py
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # The version of flake8 to use
    hooks:
    -  id: flake8
       exclude: ^dheera_ai/tests/|^dheera_ai/proxy/tests/|^dheera_ai/tests/test_dheera_ai/|^tests/test_dheera_ai/|^tests/enterprise/
       additional_dependencies: [flake8-print]
       files: (dheera_ai/|dheera_ai_proxy_extras/|enterprise/).*\.py
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        files: ^(pyproject.toml|dheera_ai-proxy-extras/pyproject.toml)$
-   repo: local
    hooks:
    -   id: check-files-match
        name: Check if files match
        entry: python3 ci_cd/check_files_match.py
        language: system