model_list:
 - model_name: gpt-4
   dheera_ai_params:
     model: openai/fake
     api_key: fake-key
     api_base: https://exampleopenaiendpoint-production.up.railway.app/
     tags: ["teamA"]
   model_info:
     id: "team-a-model"

dheera_ai_settings:
  cache: true
  callbacks: ["prometheus"]

router_settings:
  enable_tag_filtering: True # ðŸ‘ˆ Key Change

