blank_issues_enabled: true
contact_links:
  - name: Schedule Demo
    url: https://calendly.com/d/4mp-gd3-k5k/dheera_ai-1-1-onboarding-chat
    about: Speak directly with Krrish and Ishaan, the founders, to discuss issues, share feedback, or explore improvements for Dheera AI
  - name: Discord
    url: https://discord.com/invite/wuPM9dRgDw
    about: Join 250+ Dheera AI community members! 
