name: Reset dheera_ai_stable branch

on:
  release:
    types: [published, created]
jobs:
  update-stable-branch:
    if: ${{ startsWith(github.event.release.tag_name, 'v') && !endsWith(github.event.release.tag_name, '-stable') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Reset dheera_ai_stable_release_branch branch to the release commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Fetch all branches and tags
          git fetch --all

          # Check if the dheera_ai_stable_release_branch branch exists
          if git show-ref --verify --quiet refs/remotes/origin/dheera_ai_stable_release_branch; then
            echo "dheera_ai_stable_release_branch branch exists."
            git checkout dheera_ai_stable_release_branch
          else
            echo "dheera_ai_stable_release_branch branch does not exist. Creating it."
            git checkout -b dheera_ai_stable_release_branch
          fi

          # Reset dheera_ai_stable_release_branch branch to the release commit
          git reset --hard $GITHUB_SHA

          # Push the updated dheera_ai_stable_release_branch branch
          git push origin dheera_ai_stable_release_branch --force
